export {default as About} from "./About/About"
export {default as Contact} from "./Contact/Contact"
export {default as Header} from "./Header/Header"
export {default as RoadMap} from "./RoadMap/RoadMap"
export {default as Testimonial} from "./Testimonial/Testimonial"
export {default as Team} from "./Team/Team"
export {default as Sponsors} from "./Sponsors/Sponsors"
export {default as Announcements} from "./Announcements/Announcements"